[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.4"
num = "0.4.3"
pollster = "0.3.0"
softbuffer = "0.4.6"
wgpu = "22.1.0"
winit = "0.30.5"
